apiVersion: v1
kind: Service
metadata:
  name: al-helloworld
spec:
  selector:
    app: al-helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1512
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-helloworld
spec:
  selector:
    matchLabels:
      run: al-helloworld
  replicas: 2
  template:
    metadata:
      labels:
        run: al-helloworld
    spec:
      containers:
      - name: al-helloworld
        image: docker.io/kiffylee/al-helloworld
        ports:
        - containerPort: 1512